In [1]:
import pandas as pd 
import numpy as np

# Nhập Dataset & Tổng quan Dataset

In [2]:
borrower_df = pd.read_csv('Thông tin người vay nợ.csv')

In [3]:
borrower_df

,Customer_ID,Name,Age,Gender,Annual_Income,Credit_Score,Total_Debt,Employment_Status
0,C00000001,David Taylor,56,Male,133324.57,409,46843.40,Unemployed
1,C00000002,Edward Grant,69,Male,161664.22,771,34325.10,Unemployed
2,C00000003,Robert Mosley,46,Male,41999.98,696,45115.08,Unemployed
3,C00000004,Emily Cunningham,32,Male,125164.68,657,13464.71,Self-Employed
4,C00000005,Mr. Jorge Gordon,60,Male,35377.38,811,35849.70,Self-Employed
...,...,...,...,...,...,...,...,...
49995,C00049996,Tiffany Parker,66,Female,59511.55,797,37595.47,Self-Employed
49996,C00049997,Donald Martin,35,Female,86459.99,797,8756.01,Unemployed
49997,C00049998,Zachary Williams,28,Female,147893.07,492,49152.67,Employed
49998,C00049999,Andrew Schneider,59,Female,74809.49,586,3724.14,Retired
49999,C00050000,Mary Huffman,35,Male,79131.37,726,40826.36,Employed

Đây là bảng về thông tin những người vay nợ.

In [4]:
loan_df = pd.read_csv('Thông tin khoản vay.csv')

In [5]:
loan_df

,Loan_ID,Customer_ID,Loan_Amount,Interest_Rate,Loan_Term,Loan_Start_Date
0,L00000001,C00026785,40594.38,13.93,60 months,2024-06-04
1,L00000002,C00011497,38966.87,5.90,12 months,2023-09-02
2,L00000003,C00007333,29180.92,8.56,60 months,2020-08-08
3,L00000004,C00021003,31714.71,9.48,48 months,2024-06-17
4,L00000005,C00026374,19542.04,12.19,24 months,2022-10-03
...,...,...,...,...,...,...
99995,L00099996,C00013557,40113.58,4.43,24 months,2021-04-06
99996,L00099997,C00021860,29151.22,10.18,24 months,2021-07-12
99997,L00099998,C00014362,31128.74,11.15,60 months,2023-12-21
99998,L00099999,C00009310,23216.91,14.49,36 months,2024-04-12
99999,L00100000,C00048629,23276.40,6.18,12 months,2022-05-03

Đây là bảng thông tin các khoản vay tại ngân hàng.

In [6]:
default_df = pd.read_csv('Tình trạng vỡ nợ của khoản vay.csv')

In [7]:
default_df

         Loan_ID  Default
0      L00000001        0
1      L00000002        0
2      L00000003        0
3      L00000004        0
4      L00000005        0
...          ...      ...
99995  L00099996        0
99996  L00099997        0
99997  L00099998        0
99998  L00099999        0
99999  L00100000        0

[100000 rows x 2 columns]

Đây là tình trạng vỡ nợ của các khoản vay đó.

Chúng ta có 3 bảng từ đó phải gộp thành 1 bảng để dễ dàng cho việc phân tích.

In [8]:
temp_df = pd.merge(loan_df, borrower_df, on='Customer_ID', how='inner')
final_df = pd.merge(temp_df, default_df, on='Loan_ID', how='inner')
final_df

,Loan_ID,Customer_ID,Loan_Amount,Interest_Rate,Loan_Term,Loan_Start_Date,Name,Age,Gender,Annual_Income,Credit_Score,Total_Debt,Employment_Status,Default
0,L00000001,C00026785,40594.38,13.93,60 months,2024-06-04,Jimmy Smith,46,Male,102522.56,746,24487.40,Unemployed,0
1,L00000002,C00011497,38966.87,5.90,12 months,2023-09-02,Jennifer Ramirez,27,Male,83159.68,468,31885.15,Self-Employed,0
2,L00000003,C00007333,29180.92,8.56,60 months,2020-08-08,Randy Livingston,43,Female,42259.73,765,9312.03,Unemployed,0
3,L00000004,C00021003,31714.71,9.48,48 months,2024-06-17,Cynthia Boyer,58,Female,33451.08,352,42480.11,Employed,0
4,L00000005,C00026374,19542.04,12.19,24 months,2022-10-03,Brandon Hamilton,50,Male,124924.48,362,8041.98,Self-Employed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,L00099996,C00013557,40113.58,4.43,24 months,2021-04-06,Amber Mccarthy,63,Male,63119.65,619,18485.39,Self-Employed,0
99996,L00099997,C00021860,29151.22,10.18,24 months,2021-07-12,Oscar Casey,18,Male,112226.54,463,37.26,Unemployed,0
99997,L00099998,C00014362,31128.74,11.15,60 months,2023-12-21,Lisa Williams,55,Male,36768.09,621,16587.77,Self-Employed,0
99998,L00099999,C00009310,23216.91,14.49,36 months,2024-04-12,Evan Martin,67,Male,143484.42,711,36591.79,Unemployed,0
99999,L00100000,C00048629,23276.40,6.18,12 months,2022-05-03,Sherri Alvarado,36,Female,105252.03,532,9987.60,Self-Employed,0

In [9]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Loan_ID            100000 non-null  str
 1   Customer_ID        100000 non-null  str
 2   Loan_Amount        100000 non-null  float64
 3   Interest_Rate      100000 non-null  float64
 4   Loan_Term          100000 non-null  str
 5   Loan_Start_Date    100000 non-null  str
 6   Name               100000 non-null  str
 7   Age                100000 non-null  int64
 8   Gender             100000 non-null  str
 9   Annual_Income      100000 non-null  float64
 10  Credit_Score       100000 non-null  int64
 11  Total_Debt         100000 non-null  float64
 12  Employment_Status  100000 non-null  str
 13  Default            100000 non-null  int64
dtypes: float64(4), int64(3), str(7)
memory usage: 10.7 MB

Có thể thấy dữ liệu này không có khuyết thiếu dữ liệu (do tất cả đều là non-null)

## Xóa "Loan_ID" & "Customer_ID"

Ta thấy hai cột "Loan_ID" và Customer_ID" dùng để liên kết các bảng với nhau nên sau khi gộp lại thì không còn cần dùng đến nữa có thể loại bỏ.

In [10]:
final_df = final_df.drop(['Loan_ID','Customer_ID'], axis = 1)
final_df

,Loan_Amount,Interest_Rate,Loan_Term,Loan_Start_Date,Name,Age,Gender,Annual_Income,Credit_Score,Total_Debt,Employment_Status,Default
0,40594.38,13.93,60 months,2024-06-04,Jimmy Smith,46,Male,102522.56,746,24487.40,Unemployed,0
1,38966.87,5.90,12 months,2023-09-02,Jennifer Ramirez,27,Male,83159.68,468,31885.15,Self-Employed,0
2,29180.92,8.56,60 months,2020-08-08,Randy Livingston,43,Female,42259.73,765,9312.03,Unemployed,0
3,31714.71,9.48,48 months,2024-06-17,Cynthia Boyer,58,Female,33451.08,352,42480.11,Employed,0
4,19542.04,12.19,24 months,2022-10-03,Brandon Hamilton,50,Male,124924.48,362,8041.98,Self-Employed,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,40113.58,4.43,24 months,2021-04-06,Amber Mccarthy,63,Male,63119.65,619,18485.39,Self-Employed,0
99996,29151.22,10.18,24 months,2021-07-12,Oscar Casey,18,Male,112226.54,463,37.26,Unemployed,0
99997,31128.74,11.15,60 months,2023-12-21,Lisa Williams,55,Male,36768.09,621,16587.77,Self-Employed,0
99998,23216.91,14.49,36 months,2024-04-12,Evan Martin,67,Male,143484.42,711,36591.79,Unemployed,0
99999,23276.40,6.18,12 months,2022-05-03,Sherri Alvarado,36,Female,105252.03,532,9987.60,Self-Employed,0

#### Cột "Loan_Term" đang có kiểu dữ liệu str nên cần chuyển qua dạng int64 để tính toán.

In [11]:
final_df['Loan_Term'] = final_df['Loan_Term'].str.replace(' months', '').astype('int64')
final_df

,Loan_Amount,Interest_Rate,Loan_Term,Loan_Start_Date,Name,Age,Gender,Annual_Income,Credit_Score,Total_Debt,Employment_Status,Default
0,40594.38,13.93,60,2024-06-04,Jimmy Smith,46,Male,102522.56,746,24487.40,Unemployed,0
1,38966.87,5.90,12,2023-09-02,Jennifer Ramirez,27,Male,83159.68,468,31885.15,Self-Employed,0
2,29180.92,8.56,60,2020-08-08,Randy Livingston,43,Female,42259.73,765,9312.03,Unemployed,0
3,31714.71,9.48,48,2024-06-17,Cynthia Boyer,58,Female,33451.08,352,42480.11,Employed,0
4,19542.04,12.19,24,2022-10-03,Brandon Hamilton,50,Male,124924.48,362,8041.98,Self-Employed,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,40113.58,4.43,24,2021-04-06,Amber Mccarthy,63,Male,63119.65,619,18485.39,Self-Employed,0
99996,29151.22,10.18,24,2021-07-12,Oscar Casey,18,Male,112226.54,463,37.26,Unemployed,0
99997,31128.74,11.15,60,2023-12-21,Lisa Williams,55,Male,36768.09,621,16587.77,Self-Employed,0
99998,23216.91,14.49,36,2024-04-12,Evan Martin,67,Male,143484.42,711,36591.79,Unemployed,0
99999,23276.40,6.18,12,2022-05-03,Sherri Alvarado,36,Female,105252.03,532,9987.60,Self-Employed,0

In [12]:
final_df['Gender'] = final_df['Gender'].replace({'Male': 1, 'Female': 0}).astype('int64')
final_df

,Loan_Amount,Interest_Rate,Loan_Term,Loan_Start_Date,Name,Age,Gender,Annual_Income,Credit_Score,Total_Debt,Employment_Status,Default
0,40594.38,13.93,60,2024-06-04,Jimmy Smith,46,1,102522.56,746,24487.40,Unemployed,0
1,38966.87,5.90,12,2023-09-02,Jennifer Ramirez,27,1,83159.68,468,31885.15,Self-Employed,0
2,29180.92,8.56,60,2020-08-08,Randy Livingston,43,0,42259.73,765,9312.03,Unemployed,0
3,31714.71,9.48,48,2024-06-17,Cynthia Boyer,58,0,33451.08,352,42480.11,Employed,0
4,19542.04,12.19,24,2022-10-03,Brandon Hamilton,50,1,124924.48,362,8041.98,Self-Employed,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,40113.58,4.43,24,2021-04-06,Amber Mccarthy,63,1,63119.65,619,18485.39,Self-Employed,0
99996,29151.22,10.18,24,2021-07-12,Oscar Casey,18,1,112226.54,463,37.26,Unemployed,0
99997,31128.74,11.15,60,2023-12-21,Lisa Williams,55,1,36768.09,621,16587.77,Self-Employed,0
99998,23216.91,14.49,36,2024-04-12,Evan Martin,67,1,143484.42,711,36591.79,Unemployed,0
99999,23276.40,6.18,12,2022-05-03,Sherri Alvarado,36,0,105252.03,532,9987.60,Self-Employed,0

# Làm giàu dữ liệu
Chúng ta làm giàu dữ liệu bằng cách thêm các cột mới được tính toán từ các cốt trước đó.